load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "hello-time",
    srcs = ["hello-time.cc"],
    hdrs = ["hello-time.h"],
    include_prefix = "lib",
    visibility = ["//cpp/main:__pkg__"],
)
